export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const RESET_PRODUCT = 'RESET_PRODUCT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';